name: Send Email
description: Send Email 
inputs:
  VAULT_SERVER:
    description: Build Image Tag
    required: true
  VAULT_TOKEN: 
    description: Vault Token
    required: true
  VAULT_SECRETS_CICD_PATH:
    description: Vault Secrets Path
    required: true
  VAULT_SECRET_COMMON_PATH:
    description: Vault Secret Path
    required: true

runs:
  using: composite
  steps:
  - name: Import Secrets
    uses: hashicorp/vault-action@v2.4.0
    with:
      url: https://${{ inputs.VAULT_SERVER }}
      token: ${{ inputs.VAULT_TOKEN }}
      tlsSkipVerify: true
      secrets: |
        ${{inputs.VAULT_SECRETS_CICD_PATH}} EMAIL_HOST | EMAIL_HOST;
        ${{inputs.VAULT_SECRETS_CICD_PATH}} EMAIL_HOST_USER | EMAIL_HOST_USER;
        ${{inputs.VAULT_SECRETS_CICD_PATH}} EMAIL_HOST_PASSWORD | EMAIL_HOST_PASSWORD;
        ${{inputs.VAULT_SECRETS_CICD_PATH}} EMAIL_PORT | EMAIL_PORT;
        ${{inputs.VAULT_SECRET_COMMON_PATH}} TO_ADDRESS | TO_ADDRESS;

  - name: Send Mail
    uses: dawidd6/action-send-mail@v3.7.1
    with:
      server_address: ${{ env.EMAIL_HOST }}
      server_port: ${{ env.EMAIL_PORT }}
      username: ${{ env.EMAIL_HOST_USER }}
      password: ${{ env.EMAIL_HOST_PASSWORD }}
      subject: "Workflow ${{ job.status }}: ${{ github.repository }}/${{ github.workflow }}"
      body: |
          Status: ${{ job.status }}
          CommitID: ${{ github.sha }} 
          CommitMSG: ${{ github.event.head_commit.message }}
          Author: ${{ github.actor }}
          Timestamp: ${{ github.event.head_commit.timestamp }}
      from: '"deployment" <deployment@khalti.com>'
      to: ${{ env.TO_ADDRESS }}