# File: .github/actions/bandit-analysis.yml
name: Bandit Analysis
description: Analyze code with Bandit and Comment on PR

inputs:
  github_workspace:
    description: GitHub workspace path
    required: true

runs:
  using: composite
  steps:
  - name: Secret Scan
    id: trufflehog
    uses: trufflesecurity/trufflehog@main
    continue-on-error: true
    with:
      path: ${{ inputs.github_workspace }}
      base: "${{ github.event.repository.default_branch }}"
      head: HEAD
      extra_args: --debug

  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: 3.11.2
  - name: Install and scan with Bandit
    id: analyze
    run: | 
      pip install bandit
      python3 -m bandit -a file -r -ll -ii . -f csv -o report.csv --exit-zero
      python3 -m bandit -a file -r -ll -ii . -f txt -o report.txt --exit-zero

  - name: Format output for PR
    run: |
      pip install tabulate
      python3 ${{ inputs.github_workspace }}/.helpers/scripts/formater.py report.csv output.md
  - name: PR comment with file
    uses: thollander/actions-comment-pull-request@v2
    with:
      filePath: ${{ inputs.github_workspace }}/output.md