name: Send notification to Google Chats
description: Send notification to Google Chats
inputs:
  VAULT_SERVER:
    description: Build Image Tag
    required: true
  VAULT_TOKEN: 
    description: Vault Token
    required: true
  VAULT_SECRETS_CICD_PATH:
    description: Vault Secrets Path
    required: true
  VAULT_SECRET_COMMON_PATH:
    description: Notfication Message
    required: true
runs:
  using: composite
  steps:
  - name: Import Secrets From Vault
    uses: hashicorp/vault-action@v2
    with:
      url: https://${{ inputs.VAULT_SERVER }}/
      token: ${{ inputs.VAULT_TOKEN }}
      tlsSkipVerify: true
      secrets: |
        ${{ inputs.VAULT_SECRETS_CICD_PATH }} CHATS_SPACE_ID | CHATS_SPACE_ID;
        ${{ inputs.VAULT_SECRETS_CICD_PATH }} CHATS_MESSAGE_KEY | CHATS_MESSAGE_KEY;
        ${{ inputs.VAULT_SECRETS_CICD_PATH }} CHATS_TOKEN | CHATS_TOKEN;
        ${{ inputs.VAULT_SECRET_COMMON_PATH }} ENVIRONMENT | ENVIRONMENT;
        
  - name: Send notification
    run: |
       curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
                "cards": [
                  {
              "header": {
                "title": "<b>${{ github.workflow }}</b>"
              },
              "sections": [
                {
                  "widgets": [
                    {
                      "textParagraph": {
                        "text": "<b><font color=\"#00FF00\">Project: ${{ github.repository }}</font></b>"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "Status: ${{ job.status }}"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "Commit Message: ${{ github.event.head_commit.message }}"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "Environment: ${{ env.ENVIRONMENT }}"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "TimeStamp: ${{ github.event.head_commit.timestamp }}"
                      }
                    },
                    {
                      "textParagraph": {
                        "text": "<b><font color=\"#00FF00\">Author: ${{ github.actor }}</font></b>"
                      }
                    }
                  ]
                }
              ]
                  }
                ]
              }' \
              "https://chat.googleapis.com/v1/spaces/${{ env.CHATS_SPACE_ID }}/messages?key=${{ env.CHATS_MESSAGE_KEY }}&token=${{ env.CHATS_TOKEN }}"
    shell: bash