name: Dynamic Application Security Testing
description: Dynamic Application Security Testing with ZAP
inputs:
  VAULT_SERVER:
    description: VAULT Server
    type: string
  VAULT_SECRETS_PATH:
    description: VAULT secrets path
    type: string
  VAULT_TOKEN:
    description: VAULT Token
    type: string
  API_KEY:
    description: ZAP API KEY
    type: string
  ZAP_HOST:
    description: ZAP API Host
    type: string
  ZAP_PORT:
    description: ZAP API Port
    type: string
  KCR_USER:
    description: Docker User login
    type: string
  KCR_PASSWORD:
    description: Docker User Pass
    type: string
  IMAGE_REPOSITORY:
    description: Docker Image Repositories
    type: string
  TARGET:
    description: ZAP Target
    type: string

runs:
  using: composite
  steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: https://${{ inputs.VAULT_SERVER }}
        token: ${{ inputs.VAULT_TOKEN }}
        tlsSkipVerify: true
        secrets: |
          ${{ inputs.VAULT_SECRETS_PATH }} API_KEY | API_KEY;
          ${{ inputs.VAULT_SECRETS_PATH }} ZAP_HOST | ZAP_HOST;
          ${{ inputs.VAULT_SECRETS_PATH }} ZAP_PORT | ZAP_PORT;
          ${{ inputs.VAULT_CICD_PATH }} KCR_USER | KCR_USER;
          ${{ inputs.VAULT_CICD_PATH }} KCR_PASSWORD | KCR_PASSWORD;
          ${{ inputs.VAULT_CICD_PATH }} IMAGE_REPOSITORY | IMAGE_REPOSITORY;
    
    - name: Setup Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install Dependencies
      run: |
        pip install -r  ${{ github.action_path }}/scripts/requirements.txt
      shell: bash

    - name: Run ZAP Scan
      run: |
        python  ${{ github.action_path }}/scripts/zap_scan.py -ph ${{ env.ZAP_HOST }} -pp ${{ env.ZAP_PORT }} ${{ env.TARGET }} -k ${{ env.API_KEY }} -as
      shell: bash

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.IMAGE_REPOSITORY }}
        username: ${{ env.KCR_USER }}
        password: ${{ env.KCR_PASSWORD }}
      
    

    

      
  
