name: Release Tags

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Specify the release type: major, minor, or patch'
        required: true
        default: 'patch'

jobs:
  build:
    runs-on: [self-hosted, dcrunner2]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set Release Type
        id: set_release_type
        run: echo "RELEASE_TYPE=${{ github.event.inputs.release_type }}" >> $GITHUB_ENV

      - name: Generate Git Tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          CURRENT_TAG=$(git tag --list | sort -rV | head -n1)
          CURRENT_VERSION=${CURRENT_TAG#"v"}
          IFS='.' read -ra PARTS <<< "$CURRENT_VERSION"
          MAJOR=${PARTS[0]}
          MINOR=${PARTS[1]}
          PATCH=${PARTS[2]}

          RELEASE_TYPE=${{ env.RELEASE_TYPE }}

          if [ "$RELEASE_TYPE" == "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$RELEASE_TYPE" == "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "$RELEASE_TYPE" == "patch" ]; then
            PATCH=$((PATCH + 1))
          fi

          NEW_TAG="${VERSION_PREFIX}${MAJOR}.${MINOR}.${PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "system@khalti.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG
